autoInstallPeers: false
catalogMode: prefer
cleanupUnusedCatalogs: true
dangerouslyAllowAllBuilds: false
dedupePeers: true
enablePrePostScripts: false
engineStrict: true
hoist: false
hoistPattern: []
hoistWorkspacePackages: false
ignoreScripts: true
minimumReleaseAge: 10080
minimumReleaseAgeIgnoreMissingTime: true
minimumReleaseAgeStrict: true
packages:
   - 0-meta/*
   - 1-isomorphic/*
   - 2-engine--winter/*
   - 3-engine--node/*
   - 4-engine--browser/*
publicHoistPattern:
   - tslib
   - "@typescript/native-preview"
   - "@typescript"
   - tsx
   - "*oxlint*"
   - "*oxfmt*"
savePrefix: ^
shamefullyHoist: false
strictPeerDependencies: true
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 129600
verifyDepsBeforeRun: warn
catalog:
   oxfmt: ^0
